#!/usr/bin/env python3
"""Convert an unfolded text material map into a CMSSW materialBudget PSet.

The input is expected to be a tab-separated dump with columns like

  Bin_Content    Bin_Number    Bin_x_edges    Bin_y_edges
  0.0            [1, 1]        [-3000. -2995.]   [-50. -45.]

where the x axis is z in mm and the y axis is r in mm.

The output is a CMSSW python fragment containing a `cms.PSet` compatible with
the `materialBudget` parameter of the alpaka CAHitNtuplet producers.

This script can also emit lightweight SVG heatmaps without external Python
dependencies.
"""

import argparse
import copy
import math
import re
from pathlib import Path


FLOAT_RE = re.compile(r"[-+]?(?:\d+\.?\d*|\.\d+)(?:[eE][-+]?\d+)?")
INT_RE = re.compile(r"-?\d+")


def parse_args():
    parser = argparse.ArgumentParser(
        description="Convert an unfolded RZ material-budget text dump into an alpaka materialBudget PSet."
    )
    parser.add_argument("input", help="Input unfolded material-budget text file")
    parser.add_argument(
        "-o",
        "--output",
        default="pixelMaterialBudget_fromUnfolded_cfi.py",
        help="Output python fragment",
    )
    parser.add_argument("--pset-name", default="materialBudget", help="Name of the cms.PSet written to the file")
    parser.add_argument(
        "--fallback-inv-x0",
        dest="fallback_inv_x0",
        type=float,
        default=0.0,
        help="Fallback inverse radiation length in 1/cm for nonfinite bins after cropping.",
    )
    parser.add_argument("--geom-factor", type=float, default=0.7, help="Multiple-scattering geometry factor")
    parser.add_argument(
        "--fold-geom-factor",
        action="store_true",
        help=(
            "Multiply all map values, including fallback bins, by geomFactor and write geomFactor=1. "
            "Without this option the map stores physical 1/X0 and geomFactor remains separate."
        ),
    )
    parser.add_argument(
        "--z-min-cm",
        type=float,
        default=None,
        help="Optional lower z boundary in cm. Default: infer from file and convert to cm.",
    )
    parser.add_argument(
        "--z-max-cm",
        type=float,
        default=None,
        help="Optional upper z boundary in cm. Default: infer from file and convert to cm.",
    )
    parser.add_argument(
        "--r-min-cm",
        type=float,
        default=0.0,
        help="Lower r boundary in cm for the output map. Negative-r source bins are cropped away by default.",
    )
    parser.add_argument(
        "--r-max-cm",
        type=float,
        default=None,
        help="Optional upper r boundary in cm. Default: infer from file and convert to cm.",
    )
    parser.add_argument(
        "--no-symmetric-z",
        action="store_true",
        help="Write the full -z..+z map instead of the default z>=0 folded map.",
    )
    parser.add_argument(
        "--plot-prefix",
        default="",
        help=(
            "Write SVG heatmaps using this prefix. "
            "If omitted, use <output stem>. Produces *_full.svg and *_cropped.svg."
        ),
    )
    parser.add_argument(
        "--no-png-plots",
        action="store_true",
        help="Disable PNG plots even if matplotlib is available in the runtime environment.",
    )
    return parser.parse_args()


def parse_float_pair(field):
    vals = [float(x) for x in FLOAT_RE.findall(field)]
    if len(vals) != 2:
      raise ValueError(f"Could not parse float pair from field: {field!r}")
    return vals[0], vals[1]


def parse_int_pair(field):
    vals = [int(x) for x in INT_RE.findall(field)]
    if len(vals) != 2:
      raise ValueError(f"Could not parse int pair from field: {field!r}")
    return vals[0], vals[1]


def format_values(values, values_per_line=6):
    lines = []
    for start in range(0, len(values), values_per_line):
        chunk = values[start : start + values_per_line]
        lines.append("        " + ", ".join(f"{value:.9g}" for value in chunk))
    return ",\n".join(lines)


def write_pset(path, pset_name, values, geom_factor, min_z, max_z, min_r, max_r, n_bins_z, n_bins_r, source):
    content = f"""import FWCore.ParameterSet.Config as cms

# Generated by convertUnfoldedMaterialMap.py from:
#   {source}
# Flattening convention: invX0Map[rBin * matMapNBinZ + zBin]
# Units: invX0Map is 1/cm, z/r boundaries are cm.
{pset_name} = cms.PSet(
    invX0Map = cms.vdouble(
{format_values(values)}
    ),
    geomFactor = cms.double({geom_factor:.9g}),
    matMapMinZ = cms.double({min_z:.9g}),
    matMapMaxZ = cms.double({max_z:.9g}),
    matMapMinR = cms.double({min_r:.9g}),
    matMapMaxR = cms.double({max_r:.9g}),
    matMapNBinZ = cms.uint32({n_bins_z}),
    matMapNBinR = cms.uint32({n_bins_r}),
)
"""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)


def load_unfolded_map(path):
    rows = []
    with Path(path).open() as handle:
        header = next(handle, None)
        if header is None:
            raise ValueError("Input file is empty")
        for line_number, line in enumerate(handle, start=2):
            if not line.strip():
                continue
            fields = [field.strip() for field in line.split("\t") if field.strip()]
            if len(fields) != 4:
                raise ValueError(f"Line {line_number}: expected 4 tab-separated fields, got {len(fields)}")

            content = float(fields[0])
            bin_x, bin_y = parse_int_pair(fields[1])
            z_low_mm, z_high_mm = parse_float_pair(fields[2])
            r_low_mm, r_high_mm = parse_float_pair(fields[3])
            rows.append((bin_x, bin_y, z_low_mm, z_high_mm, r_low_mm, r_high_mm, content))

    if not rows:
        raise ValueError("No data rows found in input file")
    return rows


def build_source_grid(rows):
    n_bins_z = max(row[0] for row in rows)
    n_bins_r = max(row[1] for row in rows)

    z_edges_mm = [0.0] * (n_bins_z + 1)
    r_edges_mm = [0.0] * (n_bins_r + 1)
    grid = [[0.0] * n_bins_z for _ in range(n_bins_r)]

    for bin_x, bin_y, z_low_mm, z_high_mm, r_low_mm, r_high_mm, content in rows:
        z_index = bin_x - 1
        r_index = bin_y - 1
        z_edges_mm[z_index] = z_low_mm
        z_edges_mm[z_index + 1] = z_high_mm
        r_edges_mm[r_index] = r_low_mm
        r_edges_mm[r_index + 1] = r_high_mm
        grid[r_index][z_index] = content

    return grid, z_edges_mm, r_edges_mm


def find_index_for_edge(edges, value, upper=False):
    eps = 1e-9
    for i in range(len(edges) - 1):
        low = edges[i]
        high = edges[i + 1]
        if upper:
            if high <= value + eps:
                continue
            return i + 1
        if low >= value - eps:
            return i
        if low <= value < high:
            return i
    return len(edges) - 1 if upper else 0


def crop_grid(grid, z_edges_mm, r_edges_mm, z_min_mm, z_max_mm, r_min_mm, r_max_mm):
    z0 = find_index_for_edge(z_edges_mm, z_min_mm, upper=False)
    z1 = find_index_for_edge(z_edges_mm, z_max_mm, upper=True)
    r0 = find_index_for_edge(r_edges_mm, r_min_mm, upper=False)
    r1 = find_index_for_edge(r_edges_mm, r_max_mm, upper=True)

    cropped = [row[z0:z1] for row in grid[r0:r1]]
    return cropped, z_edges_mm[z0 : z1 + 1], r_edges_mm[r0 : r1 + 1]


def fold_symmetric_z(grid, z_edges_mm):
    n_bins_z = len(z_edges_mm) - 1
    centers = [0.5 * (z_edges_mm[i] + z_edges_mm[i + 1]) for i in range(n_bins_z)]
    positive_indices = [i for i, center in enumerate(centers) if center >= 0.0]

    folded = []
    for row in grid:
        new_row = []
        for i in positive_indices:
            pos_val = row[i]
            new_row.append(pos_val if math.isfinite(pos_val) else 0.0)
        folded.append(new_row)

    new_edges = [z_edges_mm[positive_indices[0]]]
    for i in positive_indices:
        new_edges.append(z_edges_mm[i + 1])
    return folded, new_edges


def flatten_values(grid, fallback_value, scale):
    values = []
    n_from_source = 0
    n_fallback = 0
    for row in grid:
        for value in row:
            if math.isfinite(value):
                values.append(value * scale)
                n_from_source += 1
            else:
                values.append(fallback_value)
                n_fallback += 1
    return values, n_from_source, n_fallback


def color_for_value(value, vmin, vmax):
    if not math.isfinite(value) or value <= 0.0:
        return "rgb(255,255,255)"
    if vmax <= vmin:
        t = 0.0
    else:
        t = (value - vmin) / (vmax - vmin)
    t = 0.0 if t < 0.0 else (1.0 if t > 1.0 else t)
    r = int(255 * t)
    g = int(255 * (1.0 - abs(2.0 * t - 1.0)))
    b = int(255 * (1.0 - t))
    return f"rgb({r},{g},{b})"


def write_svg_heatmap(path, grid, z_edges_mm, r_edges_mm, title):
    width = 1200
    height = 800
    left = 110
    right = 70
    top = 70
    bottom = 90
    plot_width = width - left - right
    plot_height = height - top - bottom

    z_min = z_edges_mm[0]
    z_max = z_edges_mm[-1]
    r_min = r_edges_mm[0]
    r_max = r_edges_mm[-1]

    positive_values = [value for row in grid for value in row if math.isfinite(value) and value > 0.0]
    vmin = min(positive_values) if positive_values else 0.0
    vmax = max(positive_values) if positive_values else 1.0

    parts = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}">',
        '<rect width="100%" height="100%" fill="white"/>',
        f'<text x="{width/2:.1f}" y="34" font-size="26" text-anchor="middle" font-family="Helvetica">{title}</text>',
        f'<rect x="{left}" y="{top}" width="{plot_width}" height="{plot_height}" fill="none" stroke="black" stroke-width="1"/>',
    ]

    for r_bin, row in enumerate(grid):
        y0 = top + plot_height * (1.0 - (r_edges_mm[r_bin + 1] - r_min) / (r_max - r_min))
        y1 = top + plot_height * (1.0 - (r_edges_mm[r_bin] - r_min) / (r_max - r_min))
        for z_bin, value in enumerate(row):
            x0 = left + plot_width * (z_edges_mm[z_bin] - z_min) / (z_max - z_min)
            x1 = left + plot_width * (z_edges_mm[z_bin + 1] - z_min) / (z_max - z_min)
            color = color_for_value(value, vmin, vmax)
            parts.append(
                f'<rect x="{x0:.3f}" y="{y0:.3f}" width="{(x1-x0):.3f}" height="{(y1-y0):.3f}" fill="{color}" stroke="none"/>'
            )

    tick_font = 16
    for frac, label in ((0.0, f"{z_min/10.0:.0f}"), (0.25, f"{(z_min + 0.25*(z_max-z_min))/10.0:.0f}"),
                        (0.5, f"{(z_min + 0.5*(z_max-z_min))/10.0:.0f}"), (0.75, f"{(z_min + 0.75*(z_max-z_min))/10.0:.0f}"),
                        (1.0, f"{z_max/10.0:.0f}")):
        x = left + plot_width * frac
        parts.append(f'<line x1="{x:.1f}" y1="{top+plot_height}" x2="{x:.1f}" y2="{top+plot_height+8}" stroke="black"/>')
        parts.append(
            f'<text x="{x:.1f}" y="{top+plot_height+28}" font-size="{tick_font}" text-anchor="middle" font-family="Helvetica">{label}</text>'
        )

    for frac, label in ((0.0, f"{r_min/10.0:.0f}"), (0.25, f"{(r_min + 0.25*(r_max-r_min))/10.0:.0f}"),
                        (0.5, f"{(r_min + 0.5*(r_max-r_min))/10.0:.0f}"), (0.75, f"{(r_min + 0.75*(r_max-r_min))/10.0:.0f}"),
                        (1.0, f"{r_max/10.0:.0f}")):
        y = top + plot_height * (1.0 - frac)
        parts.append(f'<line x1="{left-8}" y1="{y:.1f}" x2="{left}" y2="{y:.1f}" stroke="black"/>')
        parts.append(
            f'<text x="{left-14}" y="{y+5:.1f}" font-size="{tick_font}" text-anchor="end" font-family="Helvetica">{label}</text>'
        )

    parts.append(
        f'<text x="{left + plot_width/2:.1f}" y="{height-24}" font-size="20" text-anchor="middle" font-family="Helvetica">z [cm]</text>'
    )
    parts.append(
        f'<text x="28" y="{top + plot_height/2:.1f}" font-size="20" text-anchor="middle" font-family="Helvetica" transform="rotate(-90 28 {top + plot_height/2:.1f})">r [cm]</text>'
    )

    parts.append("</svg>")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(parts))


def maybe_import_matplotlib():
    try:
        import matplotlib

        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
        import numpy as np

        return plt, np
    except ImportError:
        return None, None


def write_png_heatmap(path, grid, z_edges_mm, r_edges_mm, title, plt, np):
    array = np.array(grid, dtype=float)
    array = np.ma.masked_where((array <= 0.0) | ~np.isfinite(array), array)
    fig, ax = plt.subplots(figsize=(12, 8), constrained_layout=True)
    extent = [z_edges_mm[0] / 10.0, z_edges_mm[-1] / 10.0, r_edges_mm[0] / 10.0, r_edges_mm[-1] / 10.0]
    cmap = copy.copy(plt.get_cmap())
    cmap.set_bad("white")
    image = ax.imshow(array, origin="lower", aspect="auto", extent=extent, interpolation="nearest", cmap=cmap)
    ax.set_title(title)
    ax.set_xlabel("z [cm]")
    ax.set_ylabel("r [cm]")
    cbar = fig.colorbar(image, ax=ax)
    cbar.set_label("1/X0 [1/cm]")
    path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(path, dpi=180)
    plt.close(fig)


def write_value_histogram(path, raw_grid, output_values, fallback_value, plt, np):
    raw_array = np.array(raw_grid, dtype=float).ravel()
    output_array = np.array(output_values, dtype=float)
    raw_zeros = int(np.count_nonzero(raw_array == 0.0))
    fallback = int(np.count_nonzero(np.isclose(output_array, fallback_value)))
    raw_positive = raw_array[raw_array > 0.0]
    output_positive = output_array[output_array > 0.0]

    fig, axes = plt.subplots(1, 2, figsize=(14, 5), constrained_layout=True)

    axes[0].hist(raw_array, bins=120, color="steelblue", edgecolor="none")
    axes[0].set_title("Raw Source Values")
    axes[0].set_xlabel("1/X0 [1/cm]")
    axes[0].set_ylabel("Entries")

    if output_positive.size > 0:
        axes[1].hist(output_positive, bins=120, color="darkorange", edgecolor="none", log=True)
    axes[1].set_title("Output Values")
    axes[1].set_xlabel("1/X0 [1/cm]")
    axes[1].set_ylabel("Entries")

    text = (
        f"total bins = {raw_array.size}\n"
        f"raw zero bins = {raw_zeros}\n"
        f"fallback bins = {fallback}\n"
        f"raw positive bins = {raw_positive.size}"
    )
    axes[0].text(
        0.98,
        0.98,
        text,
        transform=axes[0].transAxes,
        ha="right",
        va="top",
        fontsize=10,
        bbox=dict(boxstyle="round", facecolor="white", alpha=0.85),
    )

    path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(path, dpi=180)
    plt.close(fig)


def main():
    args = parse_args()

    rows = load_unfolded_map(args.input)
    source_grid, source_z_edges_mm, source_r_edges_mm = build_source_grid(rows)

    inferred_z_min_cm = source_z_edges_mm[0] / 10.0
    inferred_z_max_cm = source_z_edges_mm[-1] / 10.0
    inferred_r_max_cm = source_r_edges_mm[-1] / 10.0

    z_min_cm = inferred_z_min_cm if args.z_min_cm is None else args.z_min_cm
    z_max_cm = inferred_z_max_cm if args.z_max_cm is None else args.z_max_cm
    r_min_cm = args.r_min_cm
    r_max_cm = inferred_r_max_cm if args.r_max_cm is None else args.r_max_cm

    cropped_grid, cropped_z_edges_mm, cropped_r_edges_mm = crop_grid(
        source_grid,
        source_z_edges_mm,
        source_r_edges_mm,
        10.0 * z_min_cm,
        10.0 * z_max_cm,
        10.0 * r_min_cm,
        10.0 * r_max_cm,
    )

    symmetric_z = not args.no_symmetric_z
    if symmetric_z:
        cropped_grid, cropped_z_edges_mm = fold_symmetric_z(cropped_grid, cropped_z_edges_mm)

    scale = args.geom_factor if args.fold_geom_factor else 1.0
    output_geom_factor = 1.0 if args.fold_geom_factor else args.geom_factor
    fallback_value = args.fallback_inv_x0 * scale

    values, n_from_source, n_fallback = flatten_values(cropped_grid, fallback_value, scale)

    output = Path(args.output)
    plot_prefix = Path(args.plot_prefix) if args.plot_prefix else output.with_suffix("")
    write_pset(
        output,
        args.pset_name,
        values,
        output_geom_factor,
        cropped_z_edges_mm[0] / 10.0,
        cropped_z_edges_mm[-1] / 10.0,
        cropped_r_edges_mm[0] / 10.0,
        cropped_r_edges_mm[-1] / 10.0,
        len(cropped_z_edges_mm) - 1,
        len(cropped_r_edges_mm) - 1,
        args.input,
    )

    write_svg_heatmap(
        plot_prefix.with_name(plot_prefix.name + "_full.svg"),
        source_grid,
        source_z_edges_mm,
        source_r_edges_mm,
        "Unfolded Material Map (full source grid)",
    )
    write_svg_heatmap(
        plot_prefix.with_name(plot_prefix.name + "_cropped.svg"),
        cropped_grid,
        cropped_z_edges_mm,
        cropped_r_edges_mm,
        "Unfolded Material Map (cropped output grid)",
    )

    plt, np = (None, None) if args.no_png_plots else maybe_import_matplotlib()
    if plt is not None and np is not None:
        write_png_heatmap(
            plot_prefix.with_name(plot_prefix.name + "_full.png"),
            source_grid,
            source_z_edges_mm,
            source_r_edges_mm,
            "Unfolded Material Map (full source grid)",
            plt,
            np,
        )
        write_png_heatmap(
            plot_prefix.with_name(plot_prefix.name + "_cropped.png"),
            cropped_grid,
            cropped_z_edges_mm,
            cropped_r_edges_mm,
            "Unfolded Material Map (cropped output grid)",
            plt,
            np,
        )
        write_value_histogram(
            plot_prefix.with_name(plot_prefix.name + "_values.png"),
            cropped_grid,
            values,
            fallback_value,
            plt,
            np,
        )

    print(f"Wrote {output}")
    print(f"  source bins: z={len(source_z_edges_mm) - 1}, r={len(source_r_edges_mm) - 1}")
    print(f"  output bins: z={len(cropped_z_edges_mm) - 1}, r={len(cropped_r_edges_mm) - 1}, total={len(values)}")
    print(
        f"  output z range: [{cropped_z_edges_mm[0] / 10.0}, {cropped_z_edges_mm[-1] / 10.0}] cm"
        + (" (symmetric |z| fold)" if symmetric_z else "")
    )
    print(f"  output r range: [{cropped_r_edges_mm[0] / 10.0}, {cropped_r_edges_mm[-1] / 10.0}] cm")
    print(f"  finite source bins: {n_from_source}, fallback bins: {n_fallback}")
    print(f"  zero-valued source bins: {sum(1 for row in cropped_grid for value in row if value == 0.0)}")
    print(f"  fallback invX0 for nonfinite bins: {fallback_value:.9g} 1/cm")
    print(f"  output geomFactor: {output_geom_factor:.9g}")
    print(f"Wrote {plot_prefix.with_name(plot_prefix.name + '_full.svg')}")
    print(f"Wrote {plot_prefix.with_name(plot_prefix.name + '_cropped.svg')}")
    if plt is not None and np is not None:
        print(f"Wrote {plot_prefix.with_name(plot_prefix.name + '_full.png')}")
        print(f"Wrote {plot_prefix.with_name(plot_prefix.name + '_cropped.png')}")
        print(f"Wrote {plot_prefix.with_name(plot_prefix.name + '_values.png')}")


if __name__ == "__main__":
    main()
