#!/usr/bin/env python3
"""Extract an RZ pixel material map from a Validation/Geometry ROOT file.

The output is a CMSSW python fragment containing a `cms.PSet` compatible with
the `materialBudget` parameter of the alpaka CAHitNtuplet producers.
"""

import argparse
import math
import sys
from pathlib import Path


def parse_args():
    parser = argparse.ArgumentParser(
        description="Convert a local RZ material-budget histogram into an alpaka materialBudget PSet."
    )
    parser.add_argument("input", help="Input material-budget ROOT file")
    parser.add_argument(
        "-o",
        "--output",
        default="pixelMaterialBudget_cfi.py",
        help="Output python fragment",
    )
    parser.add_argument(
        "--hist",
        "--hist-name",
        dest="hist",
        default="60",
        help="Input histogram name. Default is 60: local radiation-length density in RZ.",
    )
    parser.add_argument("--pset-name", default="materialBudget", help="Name of the cms.PSet written to the file")
    parser.add_argument("--z-max", type=float, default=300.0, help="Tracker |z| extent in cm")
    parser.add_argument("--r-max", type=float, default=200.0, help="Tracker r extent in cm")
    parser.add_argument("--n-bins-z", type=int, default=300, help="Number of z bins in the output map")
    parser.add_argument("--n-bins-r", type=int, default=200, help="Number of r bins in the output map")
    parser.add_argument(
        "--no-symmetric-z",
        action="store_true",
        help="Write the full -z..+z map instead of a z>=0 map. By default the map is symmetric in z.",
    )
    parser.add_argument(
        "--fallback-inv-x0",
        "--empty-bin-inv-x0",
        dest="fallback_inv_x0",
        type=float,
        default=0.0,
        help="Fallback inverse radiation length in 1/cm for bins outside the source map or with nonfinite values.",
    )
    parser.add_argument("--geom-factor", type=float, default=0.7, help="Multiple-scattering geometry factor")
    parser.add_argument(
        "--fold-geom-factor",
        action="store_true",
        help=(
            "Multiply all map values, including fallback bins, by geomFactor and write geomFactor=1. "
            "Without this option the map stores physical 1/X0 and geomFactor remains separate."
        ),
    )
    parser.add_argument(
        "--plot-input",
        nargs="?",
        const="",
        default=None,
        metavar="PATH",
        help="Save a COLZ plot of the selected input histogram. If PATH is omitted, use <output stem>_input.png.",
    )
    parser.add_argument(
        "--plot-title",
        default="Tracker material budget",
        help="Title used for the input material-map plot.",
    )
    return parser.parse_args()


def load_root():
    try:
        import ROOT
    except ImportError:
        print("PyROOT is not available. Run this from a CMSSW runtime environment, e.g.", file=sys.stderr)
        print("  cd $CMSSW_BASE && eval $(scram runtime -sh)", file=sys.stderr)
        raise
    ROOT.gROOT.SetBatch(True)
    return ROOT


def source_bin_content(hist, z_cm, r_cm):
    xaxis = hist.GetXaxis()
    yaxis = hist.GetYaxis()
    z_mm = 10.0 * z_cm
    r_mm = 10.0 * r_cm

    if z_mm < xaxis.GetXmin() or z_mm >= xaxis.GetXmax():
        return None
    if r_mm < yaxis.GetXmin() or r_mm >= yaxis.GetXmax():
        return None

    z_bin = xaxis.FindFixBin(z_mm)
    r_bin = yaxis.FindFixBin(r_mm)
    value_per_mm = hist.GetBinContent(z_bin, r_bin)
    if not math.isfinite(value_per_mm):
        return None
    return 10.0 * value_per_mm


def format_values(values, values_per_line=6):
    lines = []
    for start in range(0, len(values), values_per_line):
        chunk = values[start : start + values_per_line]
        lines.append("        " + ", ".join(f"{value:.9g}" for value in chunk))
    return ",\n".join(lines)


def write_pset(path, pset_name, values, geom_factor, min_z, max_z, min_r, max_r, n_bins_z, n_bins_r, source):
    content = f"""import FWCore.ParameterSet.Config as cms

# Generated by extractPixelMaterialMap.py from:
#   {source}
# Flattening convention: invX0Map[rBin * matMapNBinZ + zBin]
# Units: invX0Map is 1/cm, z/r boundaries are cm.
{pset_name} = cms.PSet(
    invX0Map = cms.vdouble(
{format_values(values)}
    ),
    geomFactor = cms.double({geom_factor:.9g}),
    matMapMinZ = cms.double({min_z:.9g}),
    matMapMaxZ = cms.double({max_z:.9g}),
    matMapMinR = cms.double({min_r:.9g}),
    matMapMaxR = cms.double({max_r:.9g}),
    matMapNBinZ = cms.uint32({n_bins_z}),
    matMapNBinR = cms.uint32({n_bins_r}),
)
"""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)


def default_plot_path(output_path):
    return output_path.with_name(f"{output_path.stem}_input.png")


def save_input_plot(ROOT, hist, output_path, title):
    output_path.parent.mkdir(parents=True, exist_ok=True)
    ROOT.gStyle.SetOptStat(0)
    ROOT.gStyle.SetPalette(ROOT.kViridis)

    canvas = ROOT.TCanvas("material_input_canvas", "material input", 1100, 850)
    canvas.SetRightMargin(0.16)
    canvas.SetLeftMargin(0.12)
    canvas.SetBottomMargin(0.12)
    canvas.SetTopMargin(0.10)
    canvas.SetLogz()

    plot_hist = hist.Clone("material_input_plot")
    plot_hist.SetDirectory(0)
    plot_hist.SetTitle(title)
    plot_hist.GetXaxis().SetTitle("z [mm]")
    plot_hist.GetYaxis().SetTitle("r [mm]")
    plot_hist.GetZaxis().SetTitle("1/X_{0} [mm^{-1}]")
    plot_hist.GetXaxis().CenterTitle()
    plot_hist.GetYaxis().CenterTitle()
    plot_hist.GetXaxis().SetTitleOffset(1.1)
    plot_hist.GetYaxis().SetTitleOffset(1.25)
    plot_hist.GetZaxis().SetTitleOffset(1.25)

    min_positive = math.inf
    for z_bin in range(1, plot_hist.GetNbinsX() + 1):
        for r_bin in range(1, plot_hist.GetNbinsY() + 1):
            value = plot_hist.GetBinContent(z_bin, r_bin)
            if not math.isfinite(value) or value <= 0.0:
                # Non-positive bins are below the logarithmic color scale and
                # are therefore left unpainted on the white canvas.
                plot_hist.SetBinContent(z_bin, r_bin, 0.0)
            else:
                min_positive = min(min_positive, value)

    if not math.isfinite(min_positive):
        raise RuntimeError("The selected histogram has no positive finite bins to plot")

    plot_hist.SetMinimum(min_positive)
    plot_hist.SetContour(100)
    plot_hist.Draw("COLZ")
    canvas.Update()

    palette = plot_hist.GetListOfFunctions().FindObject("palette")
    if palette:
        palette.SetTitle("1/X_{0} [mm^{-1}]")

    canvas.SaveAs(str(output_path))


def main():
    args = parse_args()
    if args.n_bins_z <= 0 or args.n_bins_r <= 0:
        raise ValueError("Output bin counts must be positive")
    if args.z_max <= 0.0 or args.r_max <= 0.0:
        raise ValueError("Output z/r extents must be positive")

    ROOT = load_root()
    root_file = ROOT.TFile.Open(args.input)
    if not root_file or root_file.IsZombie():
        raise RuntimeError(f"Cannot open ROOT file: {args.input}")

    hist = root_file.Get(args.hist)
    if not hist:
        raise RuntimeError(f"Histogram {args.hist!r} was not found in {args.input}")
    if hist.GetDimension() != 2:
        raise RuntimeError(f"Histogram {args.hist!r} is not 2D")

    output = Path(args.output)
    if args.plot_input is not None:
        plot_output = Path(args.plot_input) if args.plot_input else default_plot_path(output)
        save_input_plot(ROOT, hist, plot_output, args.plot_title)
        print(f"Wrote input histogram plot {plot_output}")

    symmetric_z = not args.no_symmetric_z
    min_z = 0.0 if symmetric_z else -args.z_max
    max_z = args.z_max
    min_r = 0.0
    max_r = args.r_max

    scale = args.geom_factor if args.fold_geom_factor else 1.0
    output_geom_factor = 1.0 if args.fold_geom_factor else args.geom_factor
    fallback = args.fallback_inv_x0 * scale

    values = []
    n_from_source = 0
    n_fallback = 0
    for r_bin in range(args.n_bins_r):
        r = min_r + (r_bin + 0.5) * (max_r - min_r) / args.n_bins_r
        for z_bin in range(args.n_bins_z):
            z = min_z + (z_bin + 0.5) * (max_z - min_z) / args.n_bins_z
            lookup_z = abs(z) if symmetric_z else z
            value = source_bin_content(hist, lookup_z, r)
            if value is None:
                values.append(fallback)
                n_fallback += 1
            else:
                values.append(value * scale)
                n_from_source += 1

    write_pset(
        output,
        args.pset_name,
        values,
        output_geom_factor,
        min_z,
        max_z,
        min_r,
        max_r,
        args.n_bins_z,
        args.n_bins_r,
        args.input,
    )

    print(f"Wrote {output}")
    print(f"  histogram: {args.hist} ({hist.GetTitle()})")
    print(f"  bins: z={args.n_bins_z}, r={args.n_bins_r}, total={len(values)}")
    print(f"  z range: [{min_z}, {max_z}] cm {'(symmetric |z| lookup)' if symmetric_z else ''}")
    print(f"  r range: [{min_r}, {max_r}] cm")
    print(f"  finite source bins: {n_from_source}, fallback bins: {n_fallback}")
    print(f"  fallback invX0 for outside/nonfinite bins: {fallback:.9g} 1/cm")
    print(f"  output geomFactor: {output_geom_factor:.9g}")


if __name__ == "__main__":
    main()
